export const diversityIndexDataColumn = [
    { field: 'businessName', header: 'Company Name', colunName: 'Company Name', minWidth: '300px', maxWidth: 'none', textAlign: 'left', value: true },
    { field: 'supplierName', header: 'Supplier Name', colunName: 'Supplier Name', minWidth: '300px', maxWidth: '300px', textAlign: 'left', value: true },
    { field: 'companyRegNum', header: 'Company Number', colunName: 'Company Number', minWidth: '160px', maxWidth: '160px', textAlign: 'right', value: true },
    { field: 'colSupplierNumbers', header: 'Reference', colunName: 'Reference', minWidth: '120px', maxWidth: '120px', textAlign: 'right', value: true },
    { field: 'spendNet', header: 'Spend Amount', colunName: 'Spended Amount', minWidth: '150px', maxWidth: '150px', textAlign: 'right', value: true },
    { field: 'vatRegistrationNum', header: 'VAT Number', colunName: 'VAT Number', minWidth: '130px', maxWidth: '130px', textAlign: 'right', value: true },
    { field: 'is_ethnic_minority', header: 'Ethnic Minority Business', colunName: 'Ethnic Minority Business', minWidth: '220px', maxWidth: '220px', textAlign: 'center', value: true },
    { field: 'company_status', header: 'Status', colunName: 'Status', minWidth: '150px', maxWidth: '150px', textAlign: 'center', value: true },
    { field: 'dateOfCessation', header: 'Dissolved On', colunName: 'Status', minWidth: '130px', maxWidth: '130px', textAlign: 'center', value: true },
    { field: 'internationalScoreDescription', header: 'Risk Category', colunName: 'Risk Category', minWidth: '150px', maxWidth: '150px', textAlign: 'left', value: true },
    { field: 'msmeCategory', header: 'MSME Category', colunName: 'MSME Category', minWidth: '150px', maxWidth: '150px', textAlign: 'left', value: true },
    // { field: 'isEthnicOwnership', header: 'Ethnic Minority', colunName: 'Ethnic Minority', minWidth: '140px', maxWidth: '140px', textAlign: 'left', value: true },
    { field: 'femaleOwned', header: 'Woman Owned Business', colunName: 'Woman Owned Business', minWidth: '170px', maxWidth: '170px', textAlign: 'left', value: true },
    { field: 'isMilitaryVeteran', header: 'Military Veterans', colunName: 'Military Veterans', minWidth: '150px', maxWidth: '150px', textAlign: 'left', value: true },
    // { field: 'isVcseCategory', header: 'VCSE Category', colunName: 'VCSE Category', minWidth: '140px', maxWidth: '140px', textAlign: 'left', value: true },
    { field: 'isNetZeroTarget', header: 'Net-Zero Target', colunName: 'Net-Zero Target', minWidth: '160px', maxWidth: '160px', textAlign: 'left', value: true },
    { field: 'isPpcCertification', header: 'PPC Signatories', colunName: 'PPC Signatories', minWidth: '160px', maxWidth: '160px', textAlign: 'left', value: true },
    { field: 'isRaceAtWork', header: 'Race At Work', colunName: 'Race At Work', minWidth: '160px', maxWidth: '160px', textAlign: 'left', value: true },
];

export const supplierResilienceDataColumn = [
    { field: 'businessName', header: 'Company Name', colunName: 'Company Name', minWidth: '300px', maxWidth: 'none', textAlign: 'left', value: true },
    { field: 'companyRegNum', header: 'Company Number', colunName: 'Company Number', minWidth: '160px', maxWidth: '160px', textAlign: 'right', value: true },
    { field: 'msmeCategory', header: 'MSME Category', colunName: 'MSME Category', minWidth: '150px', maxWidth: '150px', textAlign: 'left', value: true },
    // { field: 'isEthnicOwnership', header: 'Ethnic Minority', colunName: 'Ethnic Minority', minWidth: '140px', maxWidth: '140px', textAlign: 'left', value: true },
    { field: 'femaleOwned', header: 'Woman Owned Business', colunName: 'Woman Owned Business', minWidth: '170px', maxWidth: '170px', textAlign: 'left', value: true },
    { field: 'isMilitaryVeteran', header: 'Military Veterans', colunName: 'Military Veterans', minWidth: '150px', maxWidth: '150px', textAlign: 'left', value: true },
    { field: 'internationalScoreDescription', header: 'Risk Category', colunName: 'Risk Category', minWidth: '150px', maxWidth: '150px', textAlign: 'left', value: true },
    { field: 'benchmarking', header: 'Benchmarking', colunName: 'Benchmarking', minWidth: '140px', maxWidth: '140px', textAlign: 'right', value: true },
    { field: 'investedCompany', header: 'Invested Company', colunName: 'Invested Company', minWidth: '150px', maxWidth: '150px', textAlign: 'center', value: true },
    { field: 'ccjCounts', header: 'Active CCJ', colunName: 'CCJ Active', minWidth: '130px', maxWidth: '130px', textAlign: 'right', value: true },
    { field: 'noOfActiveDirectors', header: 'Active Director', colunName: 'Active Director', minWidth: '150px', maxWidth: '150px', textAlign: 'right', value: true },
    { field: 'region', header: 'Region', colunName: 'Region', minWidth: '130px', maxWidth: '130px', textAlign: 'left', value: true },
    { field: 'turnover', header: 'Turnover', colunName: 'Turnover', minWidth: '140px', maxWidth: '140px', textAlign: 'right', value: true },
    { field: 'activeCharges', header: 'Active Charges', colunName: 'Active Charges', minWidth: '140px', maxWidth: '140px', textAlign: 'left', value: true },
    { field: 'propertyCount', header: 'Property Count', colunName: 'Property Count', minWidth: '150px', maxWidth: '150px', textAlign: 'left', value: true },
    { field: 'last12YearExportCount', header: 'Last 12 Months Export', colunName: 'Last 12 Months Export', minWidth: '140px', maxWidth: '140px', textAlign: 'left', value: true },
    { field: 'last12YearImportCount', header: 'Last 12 Months Import', colunName: 'Last 12 Months Import', minWidth: '140px', maxWidth: '140px', textAlign: 'left', value: true },
    // { field: 'grant', header: 'Grant', colunName: 'Grant', minWidth: '160px', maxWidth: '160px', textAlign: 'left', value: true },
    // { field: 'governmentProcurment', header: 'Government Procurement', colunName: 'Government Procurement', minWidth: '160px', maxWidth: '160px', textAlign: 'left', value: true },
    { field: 'sicCode07', header: 'SIC Code', colunName: 'SIC Code', minWidth: '250px', maxWidth: '250px', textAlign: 'left', value: true },
    { field: 'companyAge', header: "Company Age", colunName: "Company's Age", minWidth: '160px', maxWidth: '160px', textAlign: 'right', value: true },
    { field: 'lastAccountFiled', header: 'Last Account Filed', colunName: 'Last Account Filed', minWidth: '160px', maxWidth: '160px', textAlign: 'center', value: true },
    { field: 'colSupplierNumbers', header: 'Supplier Reference', colunName: 'Supplier Reference', minWidth: '160px', maxWidth: '160px', textAlign: 'right', value: true },
];