export const apiRoute = {
	"DG_API": "dg-searchApi",
	"DG_LOGIN": "dg-loginApi",
	"DG_LOGIN_API": "dg-loginApi",
	"DG_LAND_CORPORATE": "dg-landCorporateApi",
	"DG_LIST": "dg-listApi",
	"DG_LAND_REGISTRY": "dg-landRegistryApi",
	"DG_HELPDESK": "dg-helpDeskApi",
	"DG_REAL_TIME": "dg-real-time-update",
	"DG_FEATURES": "dg-featuresApi",
	"DG_PLANS": "dg-plansApi",
	"DG_PAYMENT": "dg-paymentApi",
	"DG_WEBHOOK": "dg-webhook",
	"DG_SUBSCRIPTION": "dg-subscriptionApi",
	"DG_COMPANY_DETAILS": "dg-companyDetailsApi",
	"DG_PUBLIC": "dg-publicAPIs",
	"DG_CBIL": "dg-cbilUserApi",
	"DG_DIRECTOR_DETAILS": "dg-directorsApi",
	"DG_DIRECTOR_DETAILS_2": "dg-directorApi2",
	"webstats": "webstats",
	"DG_FEEDBACK": "dg-feedbackApi",
	"DG_PEP_SANCTIONS": "dg-pepSanctionsApi",
	"DG_VALUATION": "dg-valuationPackApi",
	"DG_ISCORE": "dg-iscoreValuationApi",
	"DG_RISK_ASSESMENT": "dg-riskAssesmentsApi",
	"DG_LRM": "dg-lrmApi",
	"DG_SALESFORCE": "dg-salesforceApi",
	"DG_GULF": "dg-gulf",
	"DG_ADDON_API": "dg-addOnApi",
	"DG_USER_API": "dg-userApi",
	"DG_CHART_API": "dg-chartsApi",
	"DG_ESG_DETAILS": "dg-esgApi",
	"DG_JOB_SCHEDULER_API": "dg-jobScheduler",
	"DG_GOVTENABLER_API":"dg-govtEnablerApi",
	"DG_UPLOADCSVAPI": "dg-uploadCsvApi",
	"DG_EPC_API": "dg-epcApi",
	"api": "api/export/v1",
	"apiWithFetchEmail": "dg-companyDetailsApi",
	"contactScreenApi": "api/export",
	"REPORT": "report",
	"dg-futureGrowth": "dg-futureGrowth",
	"dg-prospensityGrowth": "dg-prospensityGrowth",
	"DG-PROMPT-AI": "api/ai",

	// For HubSpot only
	'HS_EXTENSION': 'hs-extension',

	// For Export Only
	"dev_exports": "https://devexports.datagardener.com",
	"preprod_exports": "https://preprodexports.datagardener.com",
	"live_exports": "https://exports.datagardener.com",
	"dev_exportsWithFetchMail": "https://devapi.datagardener.com",
	"preprod_exportsWithFetchMail": "https://preprodapi.datagardener.com",
	"live_exportsWithFetchMail": "https://main.datagardener.com"
};  
