interface DropdownOptType {
    label?: string,
    key?: string,
    method?: string,
    rate?: number,
    value?: number,
    icon?: string
};

export interface EnergyCarbonCalculationFieldsModelForTab extends DropdownOptType {
    energyCarbonTotal: number,
    energyCoal: DropdownOptType,
    energyDiesel: DropdownOptType,
    energyWaterConsumption: DropdownOptType,
    energyElectricity: DropdownOptType,
    energyHeatingOil: DropdownOptType,
    energyLpg: DropdownOptType,
    energyNaturalGas: DropdownOptType,
    energyWood: DropdownOptType
}
export interface EnergyCarbonCalculationFieldsModel {
    energyCarbonTotal: number,
    energyCoal: number,
    energyDiesel: number,
    energyWaterConsumption: number,
    energyElectricity: number,
    energyHeatingOil: number,
    energyLpg: number,
    energyNaturalGas: number,
    energyWood: number
}

export interface BusinessTravelCarbonCalculationFieldsModel {
    businessTravelCarbonTotal: number
    busTrainUsageByOrgzDistLocalBus: number
    busTrainUsageByOrgzNationalCoach: number
    busTrainUsageByOrgzNationalRail: number
    busTrainUsageByOrgzTramLightRail: number
    busTrainUsageByOrgzUndergroundRail: number
    macLeaseVehicleDiesel: number
    macLeaseVehicleLpg: number
    macLeaseVehiclePetrol: number
    transportFuelToSiteDiesel: number
    transportFuelToSiteLpg: number
    transportFuelToSitePetrol: number
}

export interface BusinessTravelCarbonCalculationFieldsModelForTab extends DropdownOptType {
    businessTravelCarbonTotal: number
    busTrainUsageByOrgzDistLocalBus: DropdownOptType
    busTrainUsageByOrgzNationalCoach: DropdownOptType
    busTrainUsageByOrgzNationalRail: DropdownOptType
    busTrainUsageByOrgzTramLightRail: DropdownOptType
    busTrainUsageByOrgzUndergroundRail: DropdownOptType
    macLeaseVehicleDiesel: DropdownOptType
    macLeaseVehicleLpg: DropdownOptType
    macLeaseVehiclePetrol: DropdownOptType
    transportFuelToSiteDiesel: DropdownOptType
    transportFuelToSiteLpg: DropdownOptType
    transportFuelToSitePetrol: DropdownOptType
}

export interface FlightCarbonCalculationFieldsModel {
    flightCarbonTotal: number
    totalFlyingHours: number
}
export interface FlightCarbonCalculationFieldsModelForTab extends DropdownOptType {
    flightCarbonTotal: number
    totalFlyingHours: DropdownOptType
}

export interface MaterialUseCarbonCalculationFieldsModel extends DropdownOptType {
    materialUseTotal?: number,
    muaggregates_primaryMaterialProduction?: DropdownOptType,
    muaggregates_reUsed?: DropdownOptType,
    muaggregates_openLoopSource?: DropdownOptType,
    muaggregates_closedLoopSource?: DropdownOptType,
    muAverageConstruction_primaryMaterialProduction?: DropdownOptType,
    muAsbestos_primaryMaterialProduction?: DropdownOptType,
    muAsphalt_primaryMaterialProduction?: DropdownOptType,
    muAsphalt_reUsed?: DropdownOptType,
    muAsphalt_closedLoopSource?: DropdownOptType,
    muBricks_primaryMaterialProduction?: DropdownOptType,
    muBricks_openLoopSource?: DropdownOptType,
    muConcrete_primaryMaterialProduction?: DropdownOptType,
    muConcrete_openLoopSource?: DropdownOptType,
    muConcrete_closedLoopSource?: DropdownOptType,
    muInsulation_primaryMaterialProduction?: DropdownOptType,
    muInsulation_closedLoopSource?: DropdownOptType,
    muMetals_primaryMaterialProduction?: DropdownOptType,
    muMetals_closedLoopSource?: DropdownOptType,
    muMineralOil_primaryMaterialProduction?: DropdownOptType,
    muMineralOil_closedLoopSource?: DropdownOptType,
    muPlasterboard_primaryMaterialProduction?: DropdownOptType,
    muPlasterboard_closedLoopSource?: DropdownOptType,
    muTyres_primaryMaterialProduction?: DropdownOptType,
    muTyres_reUsed?: DropdownOptType,
    muTyres_openLoopSource?: DropdownOptType,
    muWood_primaryMaterialProduction?: DropdownOptType,
    muWood_reUsed?: DropdownOptType,
    muWood_openLoopSource?: DropdownOptType,
    muWood_closedLoopSource?: DropdownOptType,
    muGlass_primaryMaterialProduction?: DropdownOptType,
    muGlass_openLoopSource?: DropdownOptType,
    muGlass_closedLoopSource?: DropdownOptType,
    muClothing_primaryMaterialProduction?: DropdownOptType,
    muClothing_reUsed?: DropdownOptType,
    muClothing_openLoopSource?: DropdownOptType,
    muFoodAndDrink_primaryMaterialProduction?: DropdownOptType,
    muCompostDerivedFromGardenWaste_primaryMaterialProduction?: DropdownOptType,
    muCompostDerivedFromFoodAndGardenWaste_primaryMaterialProduction?: DropdownOptType,
    muElectricalItemsFridgesAndFreezers_primaryMaterialProduction?: DropdownOptType,
    muElectricalitemsLarge_primaryMaterialProduction?: DropdownOptType,
    muElectricalItemsIT_primaryMaterialProduction?: DropdownOptType,
    muElectricalItemsSmall_primaryMaterialProduction?: DropdownOptType,
    muBatteriesAlkaline_primaryMaterialProduction?: DropdownOptType,
    muBatteriesLiIon_primaryMaterialProduction?: DropdownOptType,
    muBatteriesNiMh_primaryMaterialProduction?: DropdownOptType,
    muMetalAluminiumCansAndFoilExclForming_primaryMaterialProduction?: DropdownOptType,
    muMetalAluminiumCansAndFoilExclForming_closedLoopSource?: DropdownOptType,
    muMetalMixedCans_primaryMaterialProduction?: DropdownOptType,
    muMetalMixedCans_closedLoopSource?: DropdownOptType,
    muMetalScrapMetal_primaryMaterialProduction?: DropdownOptType,
    muMetalScrapMetal_closedLoopSource?: DropdownOptType,
    muMetalSteelCans_primaryMaterialProduction?: DropdownOptType,
    muMetalSteelCans_closedLoopSource?: DropdownOptType,
    muPlasticsAveragePlastics_primaryMaterialProduction?: DropdownOptType,
    muPlasticsAveragePlastics_openLoopSource?: DropdownOptType,
    muPlasticsAveragePlastics_closedLoopSource?: DropdownOptType,
    muPaperAndBoardBoard_primaryMaterialProduction?: DropdownOptType,
    muPaperAndBoardBoard_closedLoopSource?: DropdownOptType,
    muPaperAndBoardMixed_primaryMaterialProduction?: DropdownOptType,
    muPaperAndBoardMixed_closedLoopSource?: DropdownOptType,
    muPaperAndBoardPaper_primaryMaterialProduction?: DropdownOptType,
    muPaperAndBoardPaper_closedLoopSource?: DropdownOptType
}
export interface WasteManagementCarbonCalculationFieldsModel {
    wasteManagementTotal: number,
    wmaggregates_1_openLoop?: DropdownOptType,
    wmaggregates_1_closedLoop?: DropdownOptType,
    wmaggregates_1_landFill?: DropdownOptType,
    wmaverage_2_Construction_openLoop?: DropdownOptType,
    wmaverage_2_Construction_closedLoop?: DropdownOptType,
    wmasbestos_landFill?: DropdownOptType,
    wmasphalt_openLoop?: DropdownOptType,
    wmasphalt_closedLoop?: DropdownOptType,
    wmasphalt_landFill?: DropdownOptType,
    wmbricks_openLoop?: DropdownOptType,
    wmbricks_landFill?: DropdownOptType,
    wmconcrete_openLoop?: DropdownOptType,
    wmconcrete_closedLoop?: DropdownOptType,
    wmconcrete_landFill?: DropdownOptType,
    wminsulation_closedLoop?: DropdownOptType,
    wminsulation_landFill?: DropdownOptType,
    wmmetals_closedLoop?: DropdownOptType,
    wmmetals_landFill?: DropdownOptType,
    wmsoils_closedLoop?: DropdownOptType,
    wmsoils_landFill?: DropdownOptType,
    wmmineralOil_closedLoop?: DropdownOptType,
    wmmineralOil_combustion?: DropdownOptType,
    wmplasterboard_closedLoop?: DropdownOptType,
    wmplasterboard_landFill?: DropdownOptType,
    wmtyres_closedLoop?: DropdownOptType,
    wmwood_closedLoop?: DropdownOptType,
    wmwood_combustion?: DropdownOptType,
    wmwood_landFill?: DropdownOptType,
    wmclothing_closedLoop?: DropdownOptType,
    wmclothing_combustion?: DropdownOptType,
    wmclothing_landFill?: DropdownOptType,
    wmglass_openLoop?: DropdownOptType,
    wmglass_closedLoop?: DropdownOptType,
    wmglass_combustion?: DropdownOptType,
    wmglass_landFill?: DropdownOptType,
    wmmetalAluminiumCansAndFoilExclForming_openLoop?: DropdownOptType,
    wmmetalAluminiumCansAndFoilExclForming_closedLoop?: DropdownOptType,
    wmmetalAluminiumCansAndFoilExclForming_combustion?: DropdownOptType,
    wmmetalAluminiumCansAndFoilExclForming_landFill?: DropdownOptType,
    wmmetalMixedCans_openLoop?: DropdownOptType,
    wmmetalMixedCans_closedLoop?: DropdownOptType,
    wmmetalMixedCans_combustion?: DropdownOptType,
    wmmetalMixedCans_landFill?: DropdownOptType,
    wmmetalScrapMetal_openLoop?: DropdownOptType,
    wmmetalScrapMetal_closedLoop?: DropdownOptType,
    wmmetalScrapMetal_combustion?: DropdownOptType,
    wmmetalScrapMetal_landFill?: DropdownOptType,
    wmmetalSteelCans_openLoop?: DropdownOptType,
    wmmetalSteelCans_closedLoop?: DropdownOptType,
    wmmetalSteelCans_combustion?: DropdownOptType,
    wmmetalSteelCans_landFill?: DropdownOptType,
    wmplasticsAveragePlastics_openLoop?: DropdownOptType,
    wmplasticsAveragePlastics_closedLoop?: DropdownOptType,
    wmplasticsAveragePlastics_combustion?: DropdownOptType,
    wmplasticsAveragePlastics_landFill?: DropdownOptType,
    wmpaperAndBoardBoard_closedLoop?: DropdownOptType,
    wmpaperAndBoardBoard_combustion?: DropdownOptType,
    wmpaperAndBoardBoard_landFill?: DropdownOptType,
    wmpaperAndBoardMixed_closedLoop?: DropdownOptType,
    wmpaperAndBoardMixed_combustion?: DropdownOptType,
    wmpaperAndBoardMixed_ladndFill?: DropdownOptType,
    wmpaperAndBoardPaper_closedLoop?: DropdownOptType,
    wmpaperAndBoardPaper_combustion?: DropdownOptType,
    wmpaperAndBoardPaper_ladndFill?: DropdownOptType,
    wmgreenWaste_combustion?: DropdownOptType,
    wmgreenWaste_ladndFill?: DropdownOptType,
    wmcommercialAndIndustrialWaste_closedLoop?: DropdownOptType,
    wmcommercialAndIndustrialWaste_combustion?: DropdownOptType,
    wmcommercialAndIndustrialWaste_landFill?: DropdownOptType,
    wmweeeFridgesAndFreezers_openLoop?: DropdownOptType,
    wmweeeFridgesAndFreezers_landFill?: DropdownOptType,
    wmweeeLarge_openLoop?: DropdownOptType,
    wmweeeLarge_combustion?: DropdownOptType,
    wmweeeLarge_landFill?: DropdownOptType,
    wmweeeMixed_openLoop?: DropdownOptType,
    wmweeeMixed_combustion?: DropdownOptType,
    wmweeeMixed_landFill?: DropdownOptType,
    wmweeeSmall_openLoop?: DropdownOptType,
    wmweeeSmall_combustion?: DropdownOptType,
    wmweeeSmall_landFill?: DropdownOptType,
    wmwbatteries_openLoop?: DropdownOptType,
    wmwbatteries_landFill?: DropdownOptType
}

export const CarbonCalculationRatesConst: EnergyCarbonCalculationFieldsModel & BusinessTravelCarbonCalculationFieldsModel & FlightCarbonCalculationFieldsModel & MaterialUseCarbonCalculationFieldsModel & WasteManagementCarbonCalculationFieldsModel = {
    // Energy Carbon
    energyCarbonTotal: 0,
    energyCoal: 2.403,
    energyDiesel: 2.70553,
    energyWaterConsumption: 0.149,
    energyElectricity: 0.21233,
    energyHeatingOil: 2.54014,
    energyLpg: 1.55709,
    energyNaturalGas: 0.20297,
    energyWood: 0.0618,
    
    // Employee Commute Business Travel Carbon
    businessTravelCarbonTotal: 0,
    busTrainUsageByOrgzDistLocalBus: 0.1022,
    busTrainUsageByOrgzNationalCoach: 0.0268,
    busTrainUsageByOrgzNationalRail: 0.0073,
    busTrainUsageByOrgzTramLightRail: 0.0046,
    busTrainUsageByOrgzUndergroundRail: 0.0046,
    macLeaseVehicleDiesel: 2.7055,
    macLeaseVehicleLpg: 1.5570,
    macLeaseVehiclePetrol: 2.3396,
    transportFuelToSiteDiesel: 2.7055,
    transportFuelToSiteLpg: 1.5570,
    transportFuelToSitePetrol: 2.3396,

    // Flight{ rate: Carbon
    flightCarbonTotal: 0,
    totalFlyingHours: 250,

    // Material Use
    materialUseTotal: 0,
    muaggregates_primaryMaterialProduction: { rate: 7.76 },
    muaggregates_reUsed: { rate: 2.21 },
    muaggregates_openLoopSource: { rate: 3.2 }, 
    muaggregates_closedLoopSource: { rate: 3.2 },
    muAverageConstruction_primaryMaterialProduction: { rate: 79.97 },
    muAsbestos_primaryMaterialProduction: { rate: 27 },
    muAsphalt_primaryMaterialProduction: { rate: 39.21 },
    muAsphalt_reUsed: { rate: 1.74 },
    muAsphalt_closedLoopSource: { rate: 28.66 },
    muBricks_primaryMaterialProduction: { rate: 241.76 },
    muBricks_openLoopSource: { rate: 3.2 },
    muConcrete_primaryMaterialProduction: { rate: 131.76 },
    muConcrete_openLoopSource: { rate: 3.2 },
    muConcrete_closedLoopSource: { rate: 3.2 },
    muInsulation_primaryMaterialProduction: { rate: 1861.76 },
    muInsulation_closedLoopSource: { rate: 1852.09 },
    muMetals_primaryMaterialProduction: { rate: 3975.82 },
    muMetals_closedLoopSource: { rate: 571.27 },
    muMineralOil_primaryMaterialProduction: { rate: 1401.00 },
    muMineralOil_closedLoopSource: { rate: 676 },
    muPlasterboard_primaryMaterialProduction: { rate: 120.05 },
    muPlasterboard_closedLoopSource: { rate: 32.17 },
    muTyres_primaryMaterialProduction: { rate: 3335.57 },
    muTyres_reUsed: { rate: 731.22 },
    muTyres_openLoopSource: { rate: 308.4 },
    muWood_primaryMaterialProduction: { rate: 312.61 },
    muWood_reUsed: { rate: 38.54 },
    muWood_openLoopSource: { rate: 259.13 },
    muWood_closedLoopSource: { rate: 112.97 },
    muGlass_primaryMaterialProduction: { rate: 1402.77 },
    muGlass_openLoopSource: { rate: 224.76 },
    muGlass_closedLoopSource: { rate: 823.19 },
    muClothing_primaryMaterialProduction: { rate: 22310.00 },
    muClothing_reUsed: { rate: 152.25 },
    muClothing_openLoopSource: { rate: 152.25 },
    muFoodAndDrink_primaryMaterialProduction: { rate: 3701.40 },
    muCompostDerivedFromGardenWaste_primaryMaterialProduction: { rate: 113.31 },
    muCompostDerivedFromFoodAndGardenWaste_primaryMaterialProduction: { rate: 116.13 },
    muElectricalItemsFridgesAndFreezers_primaryMaterialProduction: { rate: 4363.33 },
    muElectricalitemsLarge_primaryMaterialProduction: { rate: 3267.00 },
    muElectricalItemsIT_primaryMaterialProduction: { rate: 24865.48 },
    muElectricalItemsSmall_primaryMaterialProduction: { rate: 5647.95 },
    muBatteriesAlkaline_primaryMaterialProduction: { rate: 4633.48 },
    muBatteriesLiIon_primaryMaterialProduction: { rate: 6308.00 },
    muBatteriesNiMh_primaryMaterialProduction: { rate: 28380.00 },
    muMetalAluminiumCansAndFoilExclForming_primaryMaterialProduction: { rate: 9122.64 },
    muMetalAluminiumCansAndFoilExclForming_closedLoopSource: { rate: 999.40 },
    muMetalMixedCans_primaryMaterialProduction: { rate: 5268.56 },
    muMetalMixedCans_closedLoopSource: { rate: 1473.79 },
    muMetalScrapMetal_primaryMaterialProduction: { rate: 3682.68 },
    muMetalScrapMetal_closedLoopSource: { rate: 1633.18 },
    muMetalSteelCans_primaryMaterialProduction: { rate: 3100.64 },
    muMetalSteelCans_closedLoopSource: { rate: 1740.64 }, 
    muPlasticsAveragePlastics_primaryMaterialProduction: { rate: 3116.29 },
    muPlasticsAveragePlastics_openLoopSource: { rate: 600 },
    muPlasticsAveragePlastics_closedLoopSource: { rate: 2326.53 },

    muPaperAndBoardBoard_primaryMaterialProduction: { rate: 821.23 },
    muPaperAndBoardBoard_closedLoopSource: { rate: 718.54 },
    muPaperAndBoardMixed_primaryMaterialProduction: { rate: 881.19 },
    muPaperAndBoardMixed_closedLoopSource: { rate: 731.28 },
    muPaperAndBoardPaper_primaryMaterialProduction: { rate: 919.4 },
    muPaperAndBoardPaper_closedLoopSource: { rate: 739.4 },

    // Waste Management
    wasteManagementTotal: 1,
    wmaggregates_1_openLoop: { rate: 0.9891 },
    wmaggregates_1_closedLoop: { rate: 0.989 },
    wmaggregates_1_landFill: { rate: 1.239 },
    wmaverage_2_Construction_openLoop: { rate: 0.989 },
    wmaverage_2_Construction_closedLoop: { rate: 0.989 },
    wmasbestos_landFill: { rate: 5.918 },
    wmasphalt_openLoop: { rate: 0.989 },
    wmasphalt_closedLoop: { rate: 0.989 },
    wmasphalt_landFill: { rate: 1.239 },
    wmbricks_openLoop: { rate: 0.989 },
    wmbricks_landFill: { rate: 1.239 },
    wmconcrete_openLoop: { rate: 0.989 },
    wmconcrete_closedLoop: { rate: 0.989 },
    wmconcrete_landFill: { rate: 1.239 },
    wminsulation_closedLoop: { rate: 0.989 },
    wminsulation_landFill: { rate: 1.239 },
    wmmetals_closedLoop: { rate: 0.989 },
    wmmetals_landFill: { rate: 1.264 },
    wmsoils_closedLoop: { rate: 0.989 },
    wmsoils_landFill: { rate: 17.583 },
    wmmineralOil_closedLoop: { rate: 21.294 },
    wmmineralOil_combustion: { rate: 21.294 },
    wmplasterboard_closedLoop: { rate: 21.294 },
    wmplasterboard_landFill: { rate: 71.95 },
    wmtyres_closedLoop: { rate: 21.294 },
    wmwood_closedLoop: { rate: 21.294 },
    wmwood_combustion: { rate: 21.294 },
    wmwood_landFill: { rate: 828.032 },
    wmclothing_closedLoop: { rate: 21.294 },
    wmclothing_combustion: { rate: 21.294 },
    wmclothing_landFill: { rate: 444.943 },
    wmglass_openLoop: { rate: 21.294 },
    wmglass_closedLoop: { rate: 21.294 },
    wmglass_combustion: { rate: 21.294 },
    wmglass_landFill: { rate: 8.902 },
    wmmetalAluminiumCansAndFoilExclForming_openLoop: { rate: 21 },
    wmmetalAluminiumCansAndFoilExclForming_closedLoop: { rate: 21 },
    wmmetalAluminiumCansAndFoilExclForming_combustion: { rate: 21 },
    wmmetalAluminiumCansAndFoilExclForming_landFill: { rate: 8.902 },
    wmmetalMixedCans_openLoop: { rate: 21 },
    wmmetalMixedCans_closedLoop: { rate: 21 },
    wmmetalMixedCans_combustion: { rate: 21 },
    wmmetalMixedCans_landFill: { rate: 8.902 },
    wmmetalScrapMetal_openLoop: { rate: 21 }, 
    wmmetalScrapMetal_closedLoop: { rate: 21 },
    wmmetalScrapMetal_combustion: { rate: 21 }, 
    wmmetalScrapMetal_landFill: { rate: 80902 }, 
    wmmetalSteelCans_openLoop: { rate: 21 }, 
    wmmetalSteelCans_closedLoop: { rate: 21 }, 
    wmmetalSteelCans_combustion: { rate: 21 }, 
    wmmetalSteelCans_landFill: { rate: 8.902 },
    wmplasticsAveragePlastics_openLoop: { rate: 21 }, 
    wmplasticsAveragePlastics_closedLoop: { rate: 21 }, 
    wmplasticsAveragePlastics_combustion: { rate: 21 }, 
    wmplasticsAveragePlastics_landFill: { rate: 8.902 },
    wmpaperAndBoardBoard_closedLoop: { rate: 21.294 },
    wmpaperAndBoardBoard_combustion: { rate: 21.294 },
    wmpaperAndBoardBoard_landFill: { rate: 1041.804 },
    wmpaperAndBoardMixed_closedLoop: { rate: 21.294 },
    wmpaperAndBoardMixed_combustion: { rate: 21.294 },
    wmpaperAndBoardMixed_ladndFill: { rate: 1041.804 },
    wmpaperAndBoardPaper_closedLoop: { rate: 21.294 },
    wmpaperAndBoardPaper_combustion: { rate: 21.294 },
    wmpaperAndBoardPaper_ladndFill: { rate: 1041.804 },
    wmgreenWaste_combustion: { rate: 21.294 },
    wmgreenWaste_ladndFill: { rate: 587.344 },
    wmcommercialAndIndustrialWaste_closedLoop: { rate: 21.294 },
    wmcommercialAndIndustrialWaste_combustion: { rate: 21.294 },
    wmcommercialAndIndustrialWaste_landFill: { rate: 467.046 },
    wmweeeFridgesAndFreezers_openLoop: { rate: 21.294 },
    wmweeeFridgesAndFreezers_landFill: { rate: 8.902 },
    wmweeeLarge_openLoop: { rate: 21.294 },
    wmweeeLarge_combustion: { rate: 21.294 },
    wmweeeLarge_landFill: { rate: 21.294 },
    wmweeeMixed_openLoop: { rate: 8.902 },
    wmweeeMixed_combustion: { rate: 21.294 },
    wmweeeMixed_landFill: { rate: 21.294 },
    wmweeeSmall_openLoop: { rate: 21.294 },
    wmweeeSmall_combustion: { rate: 21.294 },
    wmweeeSmall_landFill: { rate: 8.902 },
    wmwbatteries_openLoop: { rate: 21.294 },
    wmwbatteries_landFill: { rate: 8.902 }
}

export const materialUseCarbonCalculationFields: MaterialUseCarbonCalculationFieldsModel = {
    materialUseTotal: 0,
    muaggregates_primaryMaterialProduction: { label: 'Aggregates', key: 'muaggregates_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'light'},
    muaggregates_reUsed: { label: 'Aggregates', key: 'muaggregates_reUsed', method: 'Re-used', rate: 0, value: 0 , icon: 'light'},
    muaggregates_openLoopSource: { label: 'Aggregates', key: 'muaggregates_openLoopSource', method: 'Open-loop source', rate: 0, value: 0 , icon: 'light'},
    muaggregates_closedLoopSource: { label: 'Aggregates', key: 'muaggregates_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},
    muAverageConstruction_primaryMaterialProduction: { label: 'Average construction', key: 'muAverageConstruction_primaryMaterialProduction', method: 'Primary material production', icon: 'light', rate: 0, value: 0 },
    muAsbestos_primaryMaterialProduction: { label: 'Asbestos', key: 'muAsbestos_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'light'},
    muAsphalt_primaryMaterialProduction: { label: 'Asphalt', key: 'muAsphalt_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 }, icon: 'light', 
    muAsphalt_reUsed: { label: 'Asphalt', key: 'muAsphalt_reUsed', method: 'Re-used', rate: 0, value: 0, icon: 'light' }, 
    muAsphalt_closedLoopSource: { label: 'Asphalt', key: 'muAsphalt_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},
    muBricks_primaryMaterialProduction: { label: 'Bricks', key: 'muBricks_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'view_in_air'},
    muBricks_openLoopSource: { label: 'Bricks', key: 'muBricks_openLoopSource', method: 'Open-loop source', rate: 0, value: 0 , icon: 'view_in_air'},
    muConcrete_primaryMaterialProduction: { label: 'Concrete', key: 'muConcrete_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'light' }, 
    muConcrete_openLoopSource: { label: 'Concrete', key: 'muConcrete_openLoopSource', method: 'Open-loop source', rate: 0, value: 0 , icon: 'light'},
    muConcrete_closedLoopSource: { label: 'Concrete', key: 'muConcrete_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},
    muInsulation_primaryMaterialProduction: { label: 'Insulation', key: 'muInsulation_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'light'},
    muInsulation_closedLoopSource: { label: 'Insulation', key: 'muInsulation_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0, icon: 'light' }, 
    muMetals_primaryMaterialProduction: { label: 'Metals', key: 'muMetals_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'light' }, 
    muMetals_closedLoopSource: { label: 'Metals', key: 'muMetals_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0, icon: 'light' }, 
    muMineralOil_primaryMaterialProduction: { label: 'Mineral Oil', key: 'muMineralOil_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'water_drop'},
    muMineralOil_closedLoopSource: { label: 'Mineral Oil', key: 'muMineralOil_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'water_drop'},
    muPlasterboard_primaryMaterialProduction: { label: 'Plasterboard', key: 'muPlasterboard_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'feed'},
    muPlasterboard_closedLoopSource: { label: 'Plasterboard', key: 'muPlasterboard_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'feed'},
    muTyres_primaryMaterialProduction: { label: 'Tyres', key: 'muTyres_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'two_wheeler'},
    muTyres_reUsed: { label: 'Tyres', key: 'muTyres_reUsed', method: 'Re-used', rate: 0, value: 0 , icon: 'two_wheeler'},
    muTyres_openLoopSource: { label: 'Tyres', key: 'muTyres_openLoopSource', method: 'Open-loop source', rate: 0, value: 0 , icon: 'park'},
    muWood_primaryMaterialProduction:  { label: 'Wood', key: 'muWood_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'park'},
    muWood_reUsed: { label: 'Wood', key: 'muWood_reUsed', method: 'Re-used', rate: 0, value: 0 , icon: 'park'},
    muWood_openLoopSource: { label: 'Wood', key: 'muWood_openLoopSource', method: 'Open-loop source', rate: 0, value: 0 , icon: 'park'},
    muWood_closedLoopSource:  { label: 'Wood', key: 'muWood_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'park'},
    muGlass_primaryMaterialProduction: { label: 'Glass', key: 'muGlass_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'wine_bar'},
    muGlass_openLoopSource: { label: 'Glass', key: 'muGlass_openLoopSource', method: 'Open-loop source', rate: 0, value: 0 , icon: 'wine_bar'},
    muGlass_closedLoopSource: { label: 'Glass', key: 'muGlass_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'wine_bar'},
    muClothing_primaryMaterialProduction: { label: 'Clothing', key: 'muClothing_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'light'},
    muClothing_reUsed: { label: 'Clothing', key: 'muClothing_reUsed', method: 'Re-used', rate: 0, value: 0 , icon: 'light'},
    muClothing_openLoopSource: { label: 'Clothing', key: 'muClothing_openLoopSource', method: 'Open-loop source', rate: 0, value: 0, icon: 'light' }, 
    muFoodAndDrink_primaryMaterialProduction: { label: 'Food and drink', key: 'muFoodAndDrink_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'fastfood'},
    muCompostDerivedFromGardenWaste_primaryMaterialProduction: { label: 'Compost derived from garden waste', key: 'muCompostDerivedFromGardenWaste_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0,icon: 'yard' },
    muCompostDerivedFromFoodAndGardenWaste_primaryMaterialProduction: { label: 'Compost derived from food and garden waste', key: 'muCompostDerivedFromFoodAndGardenWaste_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'yard'},
    muElectricalItemsFridgesAndFreezers_primaryMaterialProduction: { label: 'Electrical items - fridges and freezers', key: 'muElectricalItemsFridgesAndFreezers_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'kitchen'},
    muElectricalitemsLarge_primaryMaterialProduction: { label: 'Electrical items - large', key: 'muElectricalitemsLarge_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'bolt' },
    muElectricalItemsIT_primaryMaterialProduction: { label: 'Electrical items - IT', key: 'muElectricalItemsIT_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'bolt' },
    muElectricalItemsSmall_primaryMaterialProduction: { label: 'Electrical items - small', key: 'muElectricalItemsSmall_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'bolt' },
    muBatteriesAlkaline_primaryMaterialProduction: { label: 'Batteries - Alkaline', key: 'muBatteriesAlkaline_primaryMaterialProduction', method: 'Primary material production', rate : 0, value: 0,icon: 'battery_alert' },
    muBatteriesLiIon_primaryMaterialProduction: { label: 'Batteries - Li ion', key: 'muBatteriesLiIon_primaryMaterialProduction', method: 'Primary material production', rate: 0, icon: 'battery_alert', value: 0 },
    muBatteriesNiMh_primaryMaterialProduction: { label: 'Batteries - NiMh', key: 'muBatteriesNiMh_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'battery_alert' },
    muMetalAluminiumCansAndFoilExclForming_primaryMaterialProduction: { label: 'Metal: aluminium cans and foil (excl. forming)', key: 'muMetalAluminiumCansAndFoilExclForming_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0 , icon: 'light'},
    muMetalAluminiumCansAndFoilExclForming_closedLoopSource: { label: 'Metal: aluminium cans and foil (excl. forming)', key: 'muMetalAluminiumCansAndFoilExclForming_closedLoopSource', icon: 'light', method: 'Primary material production', rate: 0, value: 0 },
    muMetalMixedCans_primaryMaterialProduction: { label: 'Metal: mixed cans', key: 'muMetalMixedCans_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'light' },
    muMetalMixedCans_closedLoopSource: { label: 'Metal: mixed cans', key: 'muMetalMixedCans_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},

    muMetalScrapMetal_primaryMaterialProduction: { label: 'Metal: scrap metal', key: 'muMetalScrapMetal_primaryMaterialProduction', method: 'Primary material production', rate: 0, icon: 'light', value: 0 }, 
    muMetalScrapMetal_closedLoopSource: { label: 'Metal: scrap metal', key: 'muMetalScrapMetal_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},
    muMetalSteelCans_primaryMaterialProduction: { label: 'Metal: steel cans', key: 'muMetalSteelCans_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'light' },
    muMetalSteelCans_closedLoopSource: { label: 'Metal: steel cans', key: 'muMetalSteelCans_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},
    muPlasticsAveragePlastics_primaryMaterialProduction: { label: 'Plastics: average plastics', key: 'muPlasticsAveragePlastics_primaryMaterialProduction', method: 'Primary material production', rate: 0, value: 0, icon: 'light' },
    muPlasticsAveragePlastics_openLoopSource: { label: 'Plastics: average plastics', key: 'muPlasticsAveragePlastics_openLoopSource', method: 'Open-loop source', rate: 0, value: 0 , icon: 'light'},
    muPlasticsAveragePlastics_closedLoopSource: { label: 'Plastics: average plastics', key: 'muPlasticsAveragePlastics_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0, icon: 'light' },
    muPaperAndBoardBoard_primaryMaterialProduction: { label: 'Paper and board: board', key: 'muPaperAndBoardBoard_primaryMaterialProduction', method: 'Primary material production', icon: 'light', rate: 0, value: 0 },
    muPaperAndBoardBoard_closedLoopSource: { label: 'Paper and board: board', key: 'muPlasticsAveragePlastics_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},
    muPaperAndBoardMixed_primaryMaterialProduction: { label: 'Paper and board: mixed', key: 'muPaperAndBoardMixed_primaryMaterialProduction', method: 'Primary material production', icon: 'light', rate: 0, value: 0 },
    muPaperAndBoardMixed_closedLoopSource: { label: 'Paper and board: mixed', key: 'muPaperAndBoardMixed_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},
    muPaperAndBoardPaper_primaryMaterialProduction: { label: 'Paper and board: paper', key: 'muPaperAndBoardPaper_primaryMaterialProduction', method: 'Primary material production', icon: 'light', rate: 0, value: 0 },
    muPaperAndBoardPaper_closedLoopSource: { label: 'Paper and board: paper', key: 'muPaperAndBoardPaper_closedLoopSource', method: 'Closed-loop source', rate: 0, value: 0 , icon: 'light'},
};

export const wasteManagementCarbonCalculationFields: WasteManagementCarbonCalculationFieldsModel = {
    wasteManagementTotal: 0,
    wmaggregates_1_openLoop: { label: 'Aggregates 1', key: 'wmaggregates_1_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmaggregates_1_closedLoop: { label: 'Aggregates 1', key: 'wmaggregates_1_openLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmaggregates_1_landFill: { label: 'Aggregates 1', key: 'wmaggregates_1_openLoop', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmaverage_2_Construction_openLoop: { label: 'Average 2 construction', key: 'wmaverage_2_Construction_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmaverage_2_Construction_closedLoop: { label: 'Average 2 construction', key: 'wmaverage_2_Construction_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmasbestos_landFill: { label: 'Asbestos', key: 'wmasbestos_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmasphalt_openLoop: { label: 'Asphalt', key: 'wmasbestos_landFill', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmasphalt_closedLoop: { label: 'Asphalt', key: 'wmasphalt_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmasphalt_landFill: { label: 'Asphalt', key: 'wmasphalt_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmbricks_openLoop: { label: 'Bricks', key: 'wmbricks_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'view_in_air'},
    wmbricks_landFill: { label: 'Bricks', key: 'wmasbestos_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'view_in_air'},
    wmconcrete_openLoop: { label: 'Asbestos', key: 'wmconcrete_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmconcrete_closedLoop: { label: 'Concrete', key: 'wmconcrete_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmconcrete_landFill: { label: 'Concrete', key: 'wmasbestos_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wminsulation_closedLoop: { label: 'Insulation', key: 'wminsulation_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wminsulation_landFill: { label: 'Insulation', key: 'wminsulation_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmmetals_closedLoop: { label: 'Metals', key: 'wmmetals_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmmetals_landFill: { label: 'Metals', key: 'wmmetals_closedLoop', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmsoils_closedLoop: { label: 'Soils', key: 'wmsoils_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmsoils_landFill: { label: 'Soils', key: 'wmasbestos_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmmineralOil_closedLoop: { label: 'Mineral oil', key: 'wmmineralOil_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'water_drop'},
    wmmineralOil_combustion: { label: 'Mineral oil', key: 'wmmineralOil_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'water_drop'},
    wmplasterboard_closedLoop: { label: 'Plasterboard', key: 'wmplasterboard_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'feed'},
    wmplasterboard_landFill: { label: 'Plasterboard', key: 'wmplasterboard_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'feed'},
    wmtyres_closedLoop: { label: 'Tyres', key: 'wmtyres_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'two_wheeler'},
    wmwood_closedLoop: { label: 'Wood', key: 'wmwood_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'park'},
    wmwood_combustion: { label: 'Wood', key: 'wmwood_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'park'},
    wmwood_landFill: { label: 'Wood', key: 'wmwood_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'park'},
    wmclothing_closedLoop: { label: 'Clothing', key: 'wmclothing_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmclothing_combustion: { label: 'Clothing', key: 'wmclothing_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmclothing_landFill: { label: 'Clothing', key: 'wmclothing_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmglass_openLoop: { label: 'Glass', key: 'wmglass_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'wine_bar'},
    wmglass_closedLoop: { label: 'Glass', key: 'wmglass_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'wine_bar'},
    wmglass_combustion: { label: 'Glass', key: 'wmglass_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'wine_bar'},
    wmglass_landFill: { label: 'Glass', key: 'wmglass_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'wine_bar'},
    wmmetalAluminiumCansAndFoilExclForming_openLoop: { label: 'Metal: aluminium cans and foil (excl. forming)', key: 'wmmetalAluminiumCansAndFoilExclForming_openLoop', method: 'Open Loop', rate: 0, value: 0, icon: 'recycling' },
    wmmetalAluminiumCansAndFoilExclForming_closedLoop: { label: 'Metal: aluminium cans and foil (excl. forming)', key: 'wmmetalAluminiumCansAndFoilExclForming_closedLoop', method: 'Closed Loop', rate: 0, value: 0, icon: 'recycling' },
    wmmetalAluminiumCansAndFoilExclForming_combustion: { label: 'Metal: aluminium cans and foil (excl. forming)', key: 'wmmetalAluminiumCansAndFoilExclForming_combustion', method: 'Combustion', rate: 0, value: 0, icon: 'recycling' },
    wmmetalAluminiumCansAndFoilExclForming_landFill: { label: 'Metal: aluminium cans and foil (excl. forming)', key: 'wmmetalAluminiumCansAndFoilExclForming_landFill', method: 'Landfill', rate: 0, value: 0, icon: 'recycling' },
    wmmetalMixedCans_openLoop: { label: 'Metal: mixed cans', key: 'wmmetalMixedCans_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalMixedCans_closedLoop: { label: 'Metal: mixed cans', key: 'wmmetalMixedCans_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalMixedCans_combustion: { label: 'Metal: mixed cans', key: 'wmmetalMixedCans_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalMixedCans_landFill: { label: 'Metal: mixed cans', key: 'wmmetalMixedCans_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalScrapMetal_openLoop: { label: 'Metal: scrap metal', key: 'wmmetalScrapMetal_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalScrapMetal_closedLoop: { label: 'Metal: scrap metal', key: 'wmmetalScrapMetal_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalScrapMetal_combustion: { label: 'Metal: scrap metal', key: 'wmmetalScrapMetal_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalScrapMetal_landFill: { label: 'Metal: scrap metal', key: 'wmmetalScrapMetal_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalSteelCans_openLoop: { label: 'Metal: steel cans', key: 'wmmetalSteelCans_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalSteelCans_closedLoop: { label: 'Metal: steel cans', key: 'wmmetalSteelCans_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalSteelCans_combustion: { label: 'Metal: steel cans', key: 'wmmetalSteelCans_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmmetalSteelCans_landFill: { label: 'Metal: steel cans', key: 'wmmetalSteelCans_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmplasticsAveragePlastics_openLoop: { label: 'Plastics: average plastics', key: 'wmplasticsAveragePlastics_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmplasticsAveragePlastics_closedLoop: { label: 'Plastics: average plastics', key: 'wmplasticsAveragePlastics_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmplasticsAveragePlastics_combustion: { label: 'Plastics: average plastics', key: 'wmplasticsAveragePlastics_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmplasticsAveragePlastics_landFill: { label: 'Plastics: average plastics', key: 'wmplasticsAveragePlastics_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardBoard_closedLoop: { label: 'Paper and board: board', key: 'wmpaperAndBoardBoard_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardBoard_combustion: { label: 'Paper and board: board', key: 'wmpaperAndBoardBoard_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardBoard_landFill: { label: 'Paper and board: board', key: 'wmpaperAndBoardBoard_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardMixed_closedLoop: { label: 'Paper and board: mixed', key: 'wmpaperAndBoardMixed_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardMixed_combustion: { label: 'Paper and board: mixed', key: 'wmpaperAndBoardMixed_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardMixed_ladndFill: { label: 'Paper and board: mixed', key: 'wmpaperAndBoardMixed_ladndFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardPaper_closedLoop: { label: 'Paper and board: paper', key: 'wmpaperAndBoardPaper_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardPaper_combustion: { label: 'Paper and board: paper', key: 'wmpaperAndBoardPaper_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmpaperAndBoardPaper_ladndFill: { label: 'Paper and board: paper', key: 'wmpaperAndBoardPaper_ladndFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmgreenWaste_combustion: { label: 'Greean Waste', key: 'wmgreenWaste_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmgreenWaste_ladndFill: { label: 'Greean Waste', key: 'wmgreenWaste_ladndFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmcommercialAndIndustrialWaste_closedLoop: { label: 'Commercial and industrial waste', key: 'wmcommercialAndIndustrialWaste_closedLoop', method: 'Closed Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmcommercialAndIndustrialWaste_combustion: { label: 'Commercial and industrial waste', key: 'wmcommercialAndIndustrialWaste_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmcommercialAndIndustrialWaste_landFill: { label: 'Commercial and industrial waste', key: 'wmcommercialAndIndustrialWaste_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeFridgesAndFreezers_openLoop: { label: 'WEEE - fridges and freezers', key: 'wmweeeFridgesAndFreezers_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'kitchen'},
    wmweeeFridgesAndFreezers_landFill: { label: 'WEEE - fridges and freezers', key: 'wmweeeFridgesAndFreezers_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'kitchen'},
    wmweeeLarge_openLoop: { label: 'WEEE - large', key: 'wmweeeLarge_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeLarge_combustion: { label: 'WEEE - large', key: 'wmweeeLarge_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeLarge_landFill: { label: 'WEEE - large', key: 'wmweeeLarge_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeMixed_openLoop: { label: 'WEEE - mixed', key: 'wmweeeMixed_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeMixed_combustion: { label: 'WEEE - mixed', key: 'wmweeeMixed_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeMixed_landFill: { label: 'WEEE - mixed', key: 'wmweeeMixed_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeSmall_openLoop: { label: 'WEEE - small', key: 'wmweeeSmall_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeSmall_combustion: { label: 'WEEE - small', key: 'wmweeeSmall_combustion', method: 'Combustion', rate: 0, value: 0 , icon: 'recycling'},
    wmweeeSmall_landFill: { label: 'WEEE - small', key: 'wmweeeSmall_landFill', method: 'Landfill', rate: 0, value: 0 , icon: 'recycling'},
    wmwbatteries_openLoop: { label: 'Batteries', key: 'wmwbatteries_openLoop', method: 'Open Loop', rate: 0, value: 0 , icon: 'battery_alert'},
    wmwbatteries_landFill: { label: 'Batteries', key: 'wmwbatteries_landFill', method: 'Landfill', rate: 0, value: 0, icon: 'battery_alert' }
};

export const energyCarbonCalulatedFields: EnergyCarbonCalculationFieldsModelForTab = {
    energyCarbonTotal: 0,
    energyCoal: { label: 'Coal', key: 'energyCoal', value: 0 , icon: 'light'},
    energyDiesel: { label: 'Diesel', key: 'energyDiesel', value: 0 , icon: 'oil_barrel'},
    energyWaterConsumption: { label: 'Water Consumption', key: 'energyWaterConsumption', value: 0 , icon: 'water_drop'},
    energyElectricity: { label: 'Electricity', key: 'energyElectricity', value: 0 , icon: 'light'},
    energyHeatingOil: { label: 'Heating Oil', key: 'energyHeatingOil', value: 0 , icon: 'oil_barrel'},
    energyLpg: { label: 'LPG', key: 'energyLpg', value: 0 , icon: 'propane_tank'},
    energyNaturalGas: { label: 'Natural Gas', key: 'energyNaturalGas', value: 0 , icon: 'propane_tank'},
    energyWood: { label: 'Wood', key: 'energyWood', value: 0, icon: 'park' }
};

export const businessTravelCarbonCalulatedFields: BusinessTravelCarbonCalculationFieldsModelForTab = {
    businessTravelCarbonTotal: 0,
    busTrainUsageByOrgzDistLocalBus: { label: 'Bus and Train travel (Local Bus)', key: 'busTrainUsageByOrgzDistLocalBus', value: 0 , icon: 'directions_bus'},
    busTrainUsageByOrgzNationalCoach: { label: 'Bus and Train travel (National Coach)', key: 'busTrainUsageByOrgzNationalCoach', value: 0 , icon: 'directions_bus'},
    busTrainUsageByOrgzNationalRail: { label: 'Bus and Train travel (National Rail)', key: 'busTrainUsageByOrgzNationalRail', value: 0 , icon: 'directions_bus'},
    busTrainUsageByOrgzTramLightRail: { label: 'Bus and Train travel (Tram/LightRail )', key: 'busTrainUsageByOrgzTramLightRail', value: 0 , icon: 'directions_bus'},
    busTrainUsageByOrgzUndergroundRail: { label: 'Bus and Train travel (Underground Rail)', key: 'busTrainUsageByOrgzUndergroundRail', value: 0 , icon: 'directions_bus'},
    macLeaseVehicleDiesel: { label: 'Mac vehicle/Lease vehicles (Diesel)', key: 'macLeaseVehicleDiesel', value: 0 , icon: 'directions_car'},
    macLeaseVehicleLpg: { label: 'Mac vehicle/Lease vehicles (LPG)', key: 'macLeaseVehicleLpg', value: 0 , icon: 'directions_car'},
    macLeaseVehiclePetrol: { label: 'Mac vehicle/Lease vehicles (Petrol)', key: 'macLeaseVehiclePetrol', value: 0 , icon: 'directions_car'},
    transportFuelToSiteDiesel: { label: 'Transportation of fuel to site (Diesel)', key: 'transportFuelToSiteDiesel', value: 0 , icon: 'directions_car'},
    transportFuelToSiteLpg: { label: 'Transportation of fuel to site (LPG)', key: 'transportFuelToSiteLpg', value: 0 , icon: 'directions_car'},
    transportFuelToSitePetrol: { label: 'Transportation of fuel to site (Petrol)', key: 'transportFuelToSitePetrol', value: 0, icon: 'directions_car' }
}

export const flightCarbonCalulatedFields: FlightCarbonCalculationFieldsModelForTab = {
    flightCarbonTotal: 0,
    totalFlyingHours: { label: 'Total Hours Flying', key: 'totalFlyingHours', value: 0, icon: 'flight' }
}